services:
  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    expose:
      - 5432
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
