const axios = require('axios');
const cheerio = require('cheerio');
const fs = require('fs');

const LIST = [
    "#drcl Midnight Children",
    "100 Jours Avant Ta Mort",
    "20th Century boys",
    "66,666 Years Advent Of the Dark Mage",
    "99 Reinforced Wood Stick",
    "A Couple Of Cuckoos",
    "A Returner's Magic Should be Special",
    "A Silent Voice",
    "Academy's Genius Swordmaster",
    "Adabana",
    "Ahiru no Sora",
    "Akame Ga Kill",
    "Akane Banashi",
    "Akatsuki no Yona",
    "Alice in Borderland",
    "Alice in Borderland Retry",
    "All You Need Is Kill",
    "Amour Sucré",
    "Anti Gods Dragon System",
    "Ao Ashi",
    "Ao Haru Ride",
    "Apotheosis",
    "Arcane Sniper",
    "Archmage Streamer",
    "Archmage Transcending Through Regression",
    "Area D",
    "Arifureta",
    "Asadora!",
    "ascension",
    "Astro Royale",
    "Ayakashi Triangle",
    "Ayashimon",
    "Baek XX",
    "Bâtard",
    "Be Blues!",
    "Beastars",
    "Beelzebub",
    "Berserk",
    "Berserk of Gluttony",
    "Bestiarius",
    "Black butler",
    "Black Clover",
    "Black Summoner",
    "Black Torch",
    "bleach",
    "Blue Box",
    "Blue Exorcist",
    "Blue Flag",
    "Blue Giant",
    "Blue lock",
    "Blue Period",
    "Boku no Kokoro no Yabai Yatsu",
    "Bonne nuit Punpun",
    "Boruto",
    "Boss in School",
    "Bouncer",
    "Boy's abyss",
    "Bucket List of The Dead",
    "Bungou Stray Dogs",
    "Burn the Witch",
    "Chainsaw man",
    "Cheeky Love",
    "Chi no Yume",
    "Child of the Sheath",
    "Childhood Friend of the Zenith",
    "Choujin X",
    "Chronicles of Heavenly Demon",
    "Chronicles of the Demon Faction",
    "City Hall",
    "Classroom of the Elite",
    "Clover",
    "Code Adam",
    "Code Breaker",
    "Criminelles Fiançailles",
    "Crimson Wolf",
    "D Gray Man",
    "Dai Dark",
    "Damn Reincarnation",
    "Dandadan",
    "Dark Mortal",
    "Darling in the Franxx",
    "Darwin's game",
    "Death Note",
    "Demon Evolution",
    "Demon Slave",
    "Demon slayer",
    "Denjin N",
    "Dolly Kill Kill",
    "Domestic Girlfriend",
    "Doom Breaker",
    "Dr Stone",
    "Dragon Ball super",
    "Dragon-Devouring Mage",
    "Dungeon Defense",
    "Dungeon House",
    "Dungeon Odyssey",
    "Dungeon Reset",
    "Dungeons and Artifacts",
    "Edens zero",
    "Eisen no Lovelock",
    "Eleceed",
    "Erased",
    "Estio",
    "Evil Heroes",
    "Existence",
    "Fairy Tail",
    "FFF-Class Trashero",
    "Fire Force",
    "Fire Punch",
    "Fool Night",
    "Forced to Become the Villainous Son-in-law",
    "Four Knights of the Apocalypse",
    "frieren",
    "Fullmetal Alchemist",
    "fullmetal alchemist brotherhood",
    "gachiakuta",
    "Gamaran",
    "Gamaran - Le Tournoi ultime",
    "Genesis",
    "God Of Blackfield",
    "Gokurakugai",
    "Golden Kamui",
    "Goodbye Eri",
    "Goodnight World",
    "Gosu",
    "Grand Blue",
    "Gunnm",
    "Haikyuu",
    "Hajime no Ippo",
    "Hardcore Leveling Warrior",
    "Heavenly Demon Instructor",
    "Heavenly Inquisition Sword",
    "Hell's Paradise",
    "Helmut: The Forsaken Child",
    "Her Summon",
    "Hero killer",
    "hero ticket",
    "Héros fragile",
    "Hinomaru Zumou",
    "Hoarding in Hell",
    "Homunculus",
    "Horimiya",
    "Horizon",
    "Houseki no Kuni",
    "Hunter x Hunter",
    "I Became The King by Scavenging",
    "I Grow Stronger By Eating!",
    "I Killed an Academy Player",
    "I love you, so I kill you",
    "I obtained a mythic item",
    "I Returned as an FFF-Class Witch Doctor",
    "I'll Be the Matriarch in This Life",
    "I'm Not That Kind of Talent",
    "I'm Not The Overlord !",
    "I'm the Max-Level Newbie",
    "Ijiranaide, Nagatoro-san",
    "Ikigami",
    "In the Night Consumed by Blades, I Walk",
    "Infinite Mage",
    "J'irai te voir dans ma prochaine vie",
    "Jagaaan",
    "Je suis un assassin (et je surpasse le héros)",
    "Jujutsu kaisen",
    "Jungle juice",
    "Juujika no Rokunin",
    "Juvenile Law",
    "Kagura Bachi",
    "Kaguya-sama: Love is War",
    "Kaiju N°8",
    "Kamen Byoutou",
    "Kamisama no Inai Nichiyoubi",
    "Kanojo ga Koushaku-tei ni Itta Riyuu",
    "Kanojo mo Kanojo",
    "Kaoru Hana wa Rin to Saku",
    "Kara no Kioku",
    "Karakai Jouzu no Takagi-san",
    "Kasane - La voleuse de visage",
    "Kawaii Dake Janai Shikimori-san",
    "Kemono Jihen",
    "Kengan Ashura",
    "Kengan Omega",
    "Kenshin le Vagabond",
    "Kill The Hero",
    "Killer Peter",
    "Killing Killer",
    "Killstagram",
    "kingdom",
    "Kiruru Kill Me",
    "Kobayashi's Dragon Maid",
    "Komi Can't Communicate",
    "Koroshi Ai",
    "Kowloon Generic Romance",
    "Kubo Won't Let Me Be Invisible",
    "Kuchi ga Saketemo Kimi ni wa",
    "Kumo Desu ga, Nani ka",
    "L'Atelier des Sorciers",
    "L'Expert de la Tour Tutoriel",
    "L'ère des surhommes",
    "L'impératrice remariée",
    "La duchesse déchue",
    "La Jacinthe Violette",
    "La Nuit des Démons",
    "Last Game",
    "Le Garçon au Fusil",
    "Le Péché originel de Takopi",
    "Le prix du reste de ma vie",
    "Lecteur Omniscient",
    "Legend Of The Northern Blade",
    "Les Carnets de l'Apothicaire",
    "Les Liens du Sang",
    "Les Mémoires de Vanitas",
    "Les péchés capitaux de la famille Ichinose",
    "Let's Play",
    "Leveling Up, by Only Eating!",
    "Leveling With The Gods",
    "léviathan",
    "Lightning Degree",
    "Limit Breaker",
    "Little Hands",
    "Logging 10,000 Years Into The Future",
    "Look Back",
    "Lookism",
    "Love Fragrance",
    "LUMINE",
    "Lycée post-mortem",
    "Madan no Ou to Vanadis",
    "Made in Abyss",
    "Magic Emperor",
    "Magical Girl Holy Shit",
    "Majo to Yajuu",
    "Manager kim",
    "Manchuria Opium Squad",
    "Maria no Danzai",
    "Marriage Toxin",
    "Marry my husband",
    "Martial Peak",
    "Mashle",
    "Masked Noise",
    "Maybe Meant to Be",
    "Mercenary enrollment",
    "Mission: Yozakura Family",
    "Mob Psycho 100",
    "Mon anti-fan",
    "Mon plus grand secret",
    "Monster",
    "More Than A Married Couple, But Not Lovers",
    "Moriarty The Patriot",
    "Mort Imminente",
    "Murim Login",
    "Mushoku Tensei",
    "My Dad Is Too Strong",
    "My Dress-Up Darling",
    "My Hero Academia",
    "My Home Hero",
    "My lovely Bodyguard",
    "My School-Life Pretending To Be a Worthless Person",
    "My Wife is from a Thousand Years Ago",
    "Nan Hao and Shang Feng",
    "Nan Yak",
    "Nanba MG5",
    "Nano machine",
    "Naruto",
    "Naruto Gaiden: La Spirale Au Coeur Du Tourbillon",
    "Nine Peaks",
    "Nisekoi",
    "Noblesse",
    "Noragami",
    "One Piece",
    "One punch man",
    "Operation: True Love",
    "Ordeal",
    "Orient",
    "Oshi No Ko",
    "OUT",
    "Overgeared",
    "Owari no Seraph",
    "Pandora Hearts",
    "Perfect Crime",
    "PIGPEN",
    "Platinum End",
    "player",
    "Player who returned 10 000 years later",
    "Pluto",
    "Poison City",
    "Poison Dragon The Legend of an Asura",
    "Pour le pire",
    "Prisonnier Riku",
    "Radiant",
    "Ragna Crimson",
    "Re:monster",
    "REAL",
    "Reality quest",
    "Reaper of the Drifting Moon",
    "Red Raven",
    "Regressing with the King's Power",
    "Regressor Instruction Manual",
    "Reincarnated as a Sword",
    "Reincarnation of a Martial Prodigy",
    "ReLife Player",
    "Remplacement de fortune",
    "Rendez-vous au crépuscule",
    "Rent A Girlfriend",
    "Return Of The 8th Class Magician",
    "Return of the Broken Constellation",
    "Return of the Frozen Player",
    "Return of the Iron-Blooded Hound",
    "Return Of The Legendary Spear Knight",
    "Return of the Mad Demon",
    "Return Of the SSS-Class Ranker",
    "Return to Player",
    "Rikudo",
    "Romio vs Juliet",
    "Ron Kamonohashi: Deranged Detective",
    "Roshidere",
    "Ruri Dragon",
    "Sakamoto days",
    "Sangs et papillons",
    "Sasuke Retsuden",
    "Savior of Divine Blood",
    "Second Life Ranker",
    "Seiken Gakuin no Maken Tsukai",
    "Sentai Daishikkaku",
    "Seoul Station Necromancer",
    "Seven Deadly Sins",
    "Shangri-La Frontier",
    "Shingeki no Kyojin",
    "Shinigami Bocchan to Kuro Maid",
    "SHY",
    "SK8R'S",
    "Skeleton Soldier",
    "Slam Dunk",
    "Slave B",
    "Sleeping Ranker",
    "Solo Leveling",
    "Solo Login",
    "Solo Necromancy",
    "Solo Spell Caster",
    "Soul Eater",
    "Spy X Family",
    "SSS-Class Gacha hunter",
    "SSS-Class Revival Hunter",
    "Standard of Reincarnation",
    "Star Martial God Technique",
    "Study group",
    "SubZero",
    "Super Evolution",
    "Sweet Home",
    "Swordmaster's youngest son",
    "Tales Of Demons And Gods",
    "Tengoku Daimakyou",
    "Tensei Shitara Slime Datta Ken",
    "Terror Man",
    "The Academy's Undercover Professor",
    "the Beginning After The End",
    "The boxer",
    "The Breaker",
    "The Constellation That Returned From Hell",
    "The Dark Mage’s Return to Enlistment",
    "The Descent of the Demonic Master",
    "The Druid of Seoul Station",
    "The Elusive Samurai",
    "The Eminence in Shadow",
    "The Extra’s Academy Survival Guide",
    "The Fable",
    "The Gamer",
    "The Girl From Random Chatting",
    "The Girl I Like Forgot Her Glasses",
    "The God of High School",
    "The Great Mage Returns After 4000 Years",
    "The Greatest Demon Lord Is Reborn as a Typical Nobody",
    "The Greatest Estate Developer",
    "The Heavenly Demon Can’t Live a Normal Life",
    "The Hero Returns",
    "The House Without Time",
    "The Killer Inside",
    "The Kingdoms of Ruin",
    "The Knight of Embers",
    "The Max Level Returner",
    "The Max-Level Player's 100th Regression",
    "The Newbie Is Too Strong",
    "The Novel's Extra",
    "The Player That Can't Level Up",
    "The Priest of Corruption",
    "The Promised Neverland",
    "The Quintessential Quintuplets",
    "The Regressed Son of a Duke is an Assassin",
    "The Return of the Disaster-Class Hero",
    "The Returns of The Mount Hua Sect",
    "The Rising of the Shield Hero",
    "The S-Classes That I Raised",
    "The Story Of a Manga Artist Confined by a Strange High School Girl",
    "The Terminally Ill Young Master of the Baek Clan",
    "The Unwanted Undead Adventurer",
    "The Warrior Returns",
    "The World After The Fall",
    "Time Shadows",
    "To Your Eternity",
    "Toilet-Bound Hanako-kun",
    "Tokyo Ghoul",
    "Tokyo Revengers",
    "Tokyo Underworld",
    "Tomié",
    "Tomodachi Game",
    "Tougen anki",
    "Tower Of God",
    "Trash of the Count’s Family",
    "True Beauty",
    "True Education",
    "Tsue To Tsurugi No Wistoria",
    "Tyrant of the Tower Defense Game",
    "Uchikomi, L'Esprit Du Judo",
    "Un jour à Séoul",
    "Undead Unluck",
    "unOrdinary",
    "Usogui",
    "Vagabond",
    "Versatile Mage",
    "Villain To Kill",
    "Villain Unrivaled",
    "Vinland Saga",
    "Viral Hit",
    "Webtoon Character Na Kang Lim",
    "Welcome To Demon School Iruma-kun",
    "White Blood",
    "Why I Quit Being The Demon King",
    "Wind Breaker",
    "Wind Breaker",
    "World Trigger",
    "Worn and Torn Newbie",
    "Worthless regression",
    "Wotaku ni Koi wa Muzukashii",
    "X and Ash",
    "Yakuza Reincarnation",
    "Yofukashi no Uta",
    "Yomi no Tsugai",
    "Yomotsu Hegui - Shisha no Kuni no Kajitsu",
    "Yoru Ni Naru To Boku Wa",
    "Your Name",
    "Your Talent Is Mine",
    "Zomgan"
];

async function fetchSynopsis(url, search) {
    try {
        const { data } = await axios.get(url);
        const $ = cheerio.load(data);

        let synopsisText = null;
        $('h2').each((i, elem) => {
            if ($(elem).text().includes(search)) {
                const nextElem = $(elem).next();
                if (nextElem.is('p')) {
                    synopsisText = nextElem.text();
                    console.log(`Synopsis trouvé pour ${url.split('catalogue/')[1]}`);
                    return;
                }
            }
        });

        if (synopsisText === null) {
            console.error(`Aucun synopsis trouvé pour ${url.split('catalogue/')[1]}`);
        }

        return synopsisText;
    } catch (e) {
        console.error('Erreur pendant la récupération du synopsis pour ', url.split('catalogue/')[1]);
        return null;
    }
}

function prepareMangaNameForUrl(manga) {
    return manga
        .toLowerCase()
        .replaceAll(' ', '-')
        .normalize('NFD')
        .replace(/[\u0300-\u036f]/, '')
        .replace(/[^a-zA-Z0-9- ]/, '');
}

async function fetchAllSynopsis(list) {
    const res = {};

    for (const elem of list) {
        const url = `https://anime-sama.fr/catalogue/${prepareMangaNameForUrl(String(elem))}`;
        //console.log('Search synopsis for :', url);
        const synopsis = await fetchSynopsis(url, 'Synopsis');
        if (synopsis !== null) {
            res[elem] = synopsis;
        }
    }

    return res;
}

function save(data) {
    const jsonFilePath = 'extracted.json';
    fs.writeFile(jsonFilePath, JSON.stringify(data, null, 4), 'utf8', (err) => {
        if (err) {
            console.error('Erreur lors de l\'écriture du fichier JSON:', err);
        } else {
            console.log(`Data sauvegardé dans ${jsonFilePath}`);
        }
    });
}

async function bootstrap() {
    const res = await fetchAllSynopsis(LIST);
    save(res);
}

bootstrap();
